"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useState } from "react";
import { ThemeProvider, CssBaseline } from "@mui/material";

import { ligthTeme, darkTheme } from "./theme/theme";
import "./globals.css";
import Header from "@/components/headers/Header";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isDark, setIsDark] = useState(false);

  const switchTheme: any = () => {
    setIsDark(!isDark);
  };

  return (
    <html lang="en">
      <ThemeProvider theme={isDark ? darkTheme : ligthTeme}>
        <CssBaseline />

        <body className={inter.className}>
          <Header switchTheme={switchTheme} />
          <footer></footer>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
